/**
 * Career catalog — the knowledge base behind AI Career Intelligence,
 * Skill Gap Analysis, Roadmap generation and Career Simulator.
 *
 * `skills` weights (1–3) decide how much a skill contributes to a career match,
 * which makes the engine explainable rather than opaque.
 * All copy is bilingual [english, hindi].
 */

export const CAREERS = [
  {
    id: 'software-developer',
    icon: 'Code2',
    n: ['Software Developer', 'सॉफ्टवेयर डेवलपर'],
    short: ['Build and ship product features end to end.', 'प्रोडक्ट फ़ीचर शुरू से अंत तक बनाएँ और शिप करें।'],
    difficulty: 2,
    interests: ['building-products', 'ai-research'],
    skills: [
      { id: 'dsa', w: 3 }, { id: 'javascript', w: 2 }, { id: 'python', w: 2 }, { id: 'java', w: 2 },
      { id: 'sql', w: 3 }, { id: 'git', w: 3 }, { id: 'react', w: 2 }, { id: 'node', w: 2 },
      { id: 'os', w: 2 }, { id: 'networks', w: 1 }, { id: 'sdlc', w: 2 }, { id: 'agile', w: 1 },
      { id: 'problem-solving', w: 3 }, { id: 'communication', w: 2 }, { id: 'teamwork', w: 2 },
      { id: 'documentation', w: 1 }, { id: 'testing', w: 1 },
    ],
    responsibilities: [
      ['Design, code, test and maintain application features', 'ऐप्लिकेशन फ़ीचर डिज़ाइन, कोड, टेस्ट और मेंटेन करना'],
      ['Review peer code and fix production defects', 'सहकर्मियों का कोड रिव्यू करना और प्रोडक्शन बग ठीक करना'],
      ['Work with product and design in agile sprints', 'एजाइल स्प्रिंट में प्रोडक्ट और डिज़ाइन टीम के साथ काम करना'],
      ['Write unit tests and clear technical documentation', 'यूनिट टेस्ट और स्पष्ट तकनीकी दस्तावेज़ लिखना'],
    ],
    oppCategories: [['Product engineering', 'प्रोडक्ट इंजीनियरिंग'], ['IT services', 'आईटी सेवाएँ'], ['Startups', 'स्टार्टअप'], ['Government technical posts', 'सरकारी तकनीकी पद']],
    interviewFocus: [
      ['DSA problem solving on a shared editor', 'शेयर्ड एडिटर पर DSA समस्या समाधान'],
      ['OOP, DBMS and OS fundamentals', 'OOP, DBMS और OS की बुनियाद'],
      ['One deep project walkthrough', 'एक प्रोजेक्ट की विस्तृत चर्चा'],
      ['Behavioural questions on ownership and teamwork', 'जिम्मेदारी और टीमवर्क पर व्यवहारिक प्रश्न'],
    ],
    roadmap: [
      { m: 1, title: ['Python + Git', 'पाइथन + गिट'], focus: ['Language fluency and version control habits.', 'भाषा की पकड़ और वर्ज़न कंट्रोल की आदत।'], tasks: [['Complete Python syntax, functions and OOP', 'पाइथन सिंटैक्स, फंक्शन और OOP पूरा करें', ['python']], ['Set up Git, branches and your GitHub profile', 'गिट, ब्रांच और अपना गिटहब प्रोफ़ाइल सेट करें', ['git']], ['Solve 20 easy problems', '20 आसान प्रॉब्लम हल करें', ['dsa', 'problem-solving']]] },
      { m: 2, title: ['SQL + DBMS', 'SQL + DBMS'], focus: ['Model and query data confidently.', 'डेटा को आत्मविश्वास से मॉडल और क्वेरी करें।'], tasks: [['Write joins, aggregates and subqueries daily', 'रोज़ join, aggregate और subquery लिखें', ['sql']], ['Learn normalisation and indexing', 'नॉर्मलाइज़ेशन और इंडेक्सिंग सीखें', ['dbms']], ['Build a small CRUD app with a database', 'डेटाबेस के साथ छोटा CRUD ऐप बनाएँ', ['node', 'sql']]] },
      { m: 3, title: ['Data Structures', 'डेटा स्ट्रक्चर'], focus: ['Interview-grade problem solving.', 'इंटरव्यू-स्तर की समस्या समाधान क्षमता।'], tasks: [['Arrays, strings, hashing, two pointers', 'एरे, स्ट्रिंग, हैशिंग, टू पॉइंटर', ['dsa']], ['Stacks, queues, linked lists, trees', 'स्टैक, क्यू, लिंक्ड लिस्ट, ट्री', ['dsa']], ['Timed contests: 2 per week', 'टाइम्ड कॉन्टेस्ट: सप्ताह में 2', ['problem-solving']]] },
      { m: 4, title: ['Projects', 'प्रोजेक्ट'], focus: ['Ship two portfolio projects.', 'दो पोर्टफोलियो प्रोजेक्ट शिप करें।'], tasks: [['Build a full-stack app with auth and API', 'auth और API के साथ फुल-स्टैक ऐप बनाएँ', ['react', 'node', 'sql']], ['Add tests, README and a live demo link', 'टेस्ट, README और लाइव डेमो लिंक जोड़ें', ['testing', 'documentation']], ['Publish and get one code review', 'पब्लिश करें और एक कोड रिव्यू लें', ['sdlc', 'git']]] },
      { m: 5, title: ['Resume + LinkedIn', 'रिज़्यूमे + लिंक्डइन'], focus: ['Make your work discoverable.', 'अपने काम को खोजने योग्य बनाएँ।'], tasks: [['Build an ATS-friendly resume in CareerX', 'CareerX में ATS-अनुकूल रिज़्यूमे बनाएँ', ['communication']], ['Quantify every project bullet', 'हर प्रोजेक्ट बुलेट में संख्या जोड़ें', ['documentation']], ['Complete LinkedIn with projects pinned', 'प्रोजेक्ट पिन करके लिंक्डइन पूरा करें', ['communication']]] },
      { m: 6, title: ['Interview Preparation', 'इंटरव्यू तैयारी'], focus: ['Convert preparation into offers.', 'तैयारी को ऑफ़र में बदलें।'], tasks: [['3 mock interviews in CareerX', 'CareerX में 3 मॉक इंटरव्यू', ['communication', 'problem-solving']], ['Revise OS, networks and OOP notes', 'OS, नेटवर्क और OOP नोट्स दोहराएँ', ['os', 'networks']], ['Apply to 20 matched roles weekly', 'साप्ताहिक 20 मैच्ड रोल पर आवेदन करें', ['agile']]] },
    ],
  },
  {
    id: 'data-analyst',
    icon: 'BarChart3',
    n: ['Data Analyst', 'डेटा एनालिस्ट'],
    short: ['Turn raw data into decisions stakeholders act on.', 'कच्चे डेटा को निर्णयों में बदलें।'],
    difficulty: 2,
    interests: ['data-patterns', 'business'],
    skills: [
      { id: 'sql', w: 3 }, { id: 'excel', w: 3 }, { id: 'statistics', w: 3 }, { id: 'powerbi', w: 3 },
      { id: 'python', w: 2 }, { id: 'presentation', w: 3 }, { id: 'business-analysis', w: 2 },
      { id: 'communication', w: 3 }, { id: 'problem-solving', w: 2 }, { id: 'documentation', w: 1 },
      { id: 'dbms', w: 1 },
    ],
    responsibilities: [
      ['Write SQL queries to answer business questions', 'व्यवसाय प्रश्नों के उत्तर में SQL क्वेरी लिखना'],
      ['Build dashboards and recurring reports', 'डैशबोर्ड और नियमित रिपोर्ट बनाना'],
      ['Clean, validate and document datasets', 'डेटासेट साफ़, सत्यापित और दस्तावेज़ीकृत करना'],
      ['Present findings to non-technical stakeholders', 'ग़ैर-तकनीकी हितधारकों को निष्कर्ष समझाना'],
    ],
    oppCategories: [['Analytics teams', 'एनालिटिक्स टीम'], ['BFSI & retail', 'BFSI और रिटेल'], ['Consulting', 'कंसल्टिंग'], ['Public sector data roles', 'सार्वजनिक क्षेत्र के डेटा पद']],
    interviewFocus: [
      ['Live SQL joins, window functions and case studies', 'लाइव SQL join, window फंक्शन और केस स्टडी'],
      ['Statistics: hypothesis testing and correlation', 'सांख्यिकी: हाइपोथिसिस टेस्टिंग और सहसंबंध'],
      ['Dashboard critique and metric selection', 'डैशबोर्ड समीक्षा और मेट्रिक चयन'],
      ['Explaining an insight to a non-technical audience', 'ग़ैर-तकनीकी दर्शक को अंतर्दृष्टि समझाना'],
    ],
    roadmap: [
      { m: 1, title: ['Excel + Statistics', 'एक्सेल + सांख्यिकी'], focus: ['Analytical foundations before tools.', 'टूल्स से पहले विश्लेषण की नींव।'], tasks: [['Pivot tables, lookups and charting', 'पिवट टेबल, लुकअप और चार्टिंग', ['excel']], ['Descriptive stats, distributions, correlation', 'वर्णनात्मक सांख्यिकी, वितरण, सहसंबंध', ['statistics']], ['Analyse one open dataset end to end', 'एक ओपन डेटासेट का पूर्ण विश्लेषण', ['problem-solving']]] },
      { m: 2, title: ['SQL + DBMS', 'SQL + DBMS'], focus: ['The core analyst skill.', 'एनालिस्ट का मुख्य कौशल।'], tasks: [['Joins, group by, having, subqueries', 'join, group by, having, subquery', ['sql']], ['Window functions and CTEs', 'विंडो फंक्शन और CTE', ['sql']], ['Model a small business schema', 'छोटा बिज़नेस स्कीमा मॉडल करें', ['dbms']]] },
      { m: 3, title: ['Python for Analysis', 'विश्लेषण के लिए पाइथन'], focus: ['Go beyond spreadsheet limits.', 'स्प्रेडशीट की सीमा से आगे बढ़ें।'], tasks: [['Pandas cleaning and aggregation', 'पांडास क्लीनिंग और एग्रीगेशन', ['python']], ['Matplotlib / Seaborn visuals', 'मैटप्लॉटलिब / सीबोर्न विज़ुअल', ['python']], ['Automate one weekly report', 'एक साप्ताहिक रिपोर्ट स्वचालित करें', ['python']]] },
      { m: 4, title: ['Dashboards + Projects', 'डैशबोर्ड + प्रोजेक्ट'], focus: ['Show, don’t just tell.', 'केवल बताएँ नहीं, दिखाएँ।'], tasks: [['Build a Power BI / Tableau dashboard', 'पावर BI / टैब्लो डैशबोर्ड बनाएँ', ['powerbi']], ['Write the business question it answers', 'वह व्यवसाय प्रश्न लिखें जिसका यह उत्तर देता है', ['business-analysis']], ['Record a 3-minute walkthrough', '3 मिनट का वॉकथ्रू रिकॉर्ड करें', ['presentation']]] },
      { m: 5, title: ['Resume + Portfolio', 'रिज़्यूमे + पोर्टफोलियो'], focus: ['Package insights as proof.', 'अंतर्दृष्टि को प्रमाण की तरह प्रस्तुत करें।'], tasks: [['Analyst resume with metric-led bullets', 'मेट्रिक-आधारित बुलेट वाला एनालिस्ट रिज़्यूमे', ['communication']], ['Publish 3 case studies with visuals', '3 केस स्टडी विज़ुअल के साथ पब्लिश करें', ['documentation']], ['Add SQL and BI keywords for ATS', 'ATS के लिए SQL और BI कीवर्ड जोड़ें', ['communication']]] },
      { m: 6, title: ['Case Interviews', 'केस इंटरव्यू'], focus: ['Think aloud, structured.', 'संरचित रूप से बोलते हुए सोचें।'], tasks: [['3 mock analyst interviews', '3 मॉक एनालिस्ट इंटरव्यू', ['communication']], ['Practise guesstimates and metric trees', 'गेसटीमेट और मेट्रिक ट्री का अभ्यास', ['problem-solving']], ['Apply to matched analyst roles', 'मैच्ड एनालिस्ट रोल पर आवेदन', ['business-analysis']]] },
    ],
  },
  {
    id: 'ai-ml-engineer',
    icon: 'BrainCircuit',
    n: ['AI / ML Engineer', 'AI / ML इंजीनियर'],
    short: ['Design, train and deploy intelligent systems.', 'बुद्धिमान सिस्टम डिज़ाइन, ट्रेन और डिप्लॉय करें।'],
    difficulty: 3,
    interests: ['ai-research', 'data-patterns'],
    skills: [
      { id: 'python', w: 3 }, { id: 'ml', w: 3 }, { id: 'statistics', w: 3 }, { id: 'dsa', w: 2 },
      { id: 'sql', w: 2 }, { id: 'git', w: 3 }, { id: 'docker', w: 2 }, { id: 'cloud', w: 2 },
      { id: 'problem-solving', w: 3 }, { id: 'documentation', w: 2 }, { id: 'presentation', w: 2 },
      { id: 'linux', w: 1 },
    ],
    responsibilities: [
      ['Build data pipelines and feature engineering', 'डेटा पाइपलाइन और फ़ीचर इंजीनियरिंग बनाना'],
      ['Train, evaluate and version models', 'मॉडल ट्रेन, मूल्यांकन और वर्ज़न करना'],
      ['Deploy models behind APIs and monitor drift', 'मॉडल को API के पीछे डिप्लॉय करना और ड्रिफ्ट मॉनिटर करना'],
      ['Document experiments and results', 'प्रयोग और परिणाम दस्तावेज़ीकृत करना'],
    ],
    oppCategories: [['AI product teams', 'AI प्रोडक्ट टीम'], ['Research labs', 'रिसर्च लैब'], ['Analytics consultancies', 'एनालिटिक्स कंसल्टेंसी'], ['Higher studies / GATE', 'उच्च शिक्षा / GATE']],
    interviewFocus: [
      ['ML theory: bias-variance, regularisation, metrics', 'ML सिद्धांत: बायस-वेरिएंस, रेगुलराइज़ेशन, मेट्रिक्स'],
      ['Coding: Python + DSA at moderate difficulty', 'कोडिंग: पाइथन + मध्यम स्तर का DSA'],
      ['System design for an ML feature', 'ML फ़ीचर का सिस्टम डिज़ाइन'],
      ['Deep walkthrough of one project you trained', 'आपके ट्रेन किए एक प्रोजेक्ट की विस्तृत चर्चा'],
    ],
    roadmap: [
      { m: 1, title: ['Python + Maths', 'पाइथन + गणित'], focus: ['NumPy, linear algebra, probability.', 'नमपाई, रैखिक बीजगणित, प्रायिकता।'], tasks: [['NumPy and Pandas fluency', 'नमपाई और पांडास में दक्षता', ['python']], ['Linear algebra and probability refresh', 'रैखिक बीजगणित और प्रायिकता दोहराएँ', ['statistics']], ['Git for experiments', 'प्रयोगों के लिए गिट', ['git']]] },
      { m: 2, title: ['Classical ML', 'क्लासिकल ML'], focus: ['Understand before deep learning.', 'डीप लर्निंग से पहले समझें।'], tasks: [['Regression, classification, trees, ensembles', 'रिग्रेशन, क्लासिफ़िकेशन, ट्री, एनसेंबल', ['ml']], ['Cross-validation and metrics', 'क्रॉस-वैलिडेशन और मेट्रिक्स', ['ml', 'statistics']], ['One Kaggle-style dataset end to end', 'एक कगgle-शैली डेटासेट पूरा करें', ['ml']]] },
      { m: 3, title: ['Deep Learning', 'डीप लर्निंग'], focus: ['Neural networks and frameworks.', 'न्यूरल नेटवर्क और फ्रेमवर्क।'], tasks: [['NN fundamentals, backpropagation', 'NN की बुनियाद, बैकप्रोपेगेशन', ['ml']], ['CNN or transformer project', 'CNN या ट्रांसफ़ॉर्मर प्रोजेक्ट', ['ml', 'python']], ['Track experiments properly', 'प्रयोग सही तरह ट्रैक करें', ['documentation']]] },
      { m: 4, title: ['MLOps + Projects', 'MLOps + प्रोजेक्ट'], focus: ['Ship a model, not a notebook.', 'नोटबुक नहीं, मॉडल शिप करें।'], tasks: [['Wrap a model in a FastAPI service', 'मॉडल को FastAPI सेवा में लपेटें', ['node', 'docker']], ['Containerise with Docker', 'डॉकर से कंटेनराइज़ करें', ['docker']], ['Deploy to a free cloud tier', 'मुफ़्त क्लाउड टियर पर डिप्लॉय करें', ['cloud']]] },
      { m: 5, title: ['Portfolio + Resume', 'पोर्टफोलियो + रिज़्यूमे'], focus: ['Explain impact, not algorithms.', 'अल्गोरिदम नहीं, प्रभाव समझाएँ।'], tasks: [['Write a technical blog per project', 'हर प्रोजेक्ट पर तकनीकी ब्लॉग लिखें', ['documentation', 'presentation']], ['ML-focused ATS resume', 'ML-केंद्रित ATS रिज़्यूमे', ['communication']], ['Publish reproducible repos', 'पुनरुत्पादनीय repo पब्लिश करें', ['git']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Theory + coding + system design.', 'सिद्धांत + कोडिंग + सिस्टम डिज़ाइन।'], tasks: [['3 AI/ML mock interviews', '3 AI/ML मॉक इंटरव्यू', ['communication']], ['Revise ML theory flashcards', 'ML सिद्धांत फ्लैशकार्ड दोहराएँ', ['ml']], ['DSA practice 3x weekly', 'सप्ताह में 3 बार DSA अभ्यास', ['dsa']]] },
    ],
  },
  {
    id: 'cloud-devops',
    icon: 'Cloud',
    n: ['Cloud / DevOps Engineer', 'क्लाउड / डेवऑप्स इंजीनियर'],
    short: ['Automate infrastructure and keep systems reliable.', 'इंफ्रास्ट्रक्चर स्वचालित करें और सिस्टम विश्वसनीय रखें।'],
    difficulty: 3,
    interests: ['infra', 'building-products'],
    skills: [
      { id: 'linux', w: 3 }, { id: 'cloud', w: 3 }, { id: 'docker', w: 3 }, { id: 'networks', w: 3 },
      { id: 'python', w: 2 }, { id: 'git', w: 3 }, { id: 'os', w: 2 }, { id: 'security-basics', w: 2 },
      { id: 'documentation', w: 2 }, { id: 'problem-solving', w: 2 }, { id: 'time-management', w: 1 },
      { id: 'agile', w: 1 },
    ],
    responsibilities: [
      ['Build CI/CD pipelines and automation scripts', 'CI/CD पाइपलाइन और ऑटोमेशन स्क्रिप्ट बनाना'],
      ['Provision and monitor cloud infrastructure', 'क्लाउड इंफ्रास्ट्रक्चर तैयार और मॉनिटर करना'],
      ['Containerise services and manage deployments', 'सेवाओं को कंटेनराइज़ करना और डिप्लॉयमेंट प्रबंधित करना'],
      ['Respond to incidents and improve reliability', 'घटनाओं पर प्रतिक्रिया और विश्वसनीयता सुधारना'],
    ],
    oppCategories: [['Cloud platform teams', 'क्लाउड प्लेटफ़ॉर्म टीम'], ['SRE / operations', 'SRE / संचालन'], ['Managed service providers', 'मैनेज्ड सेवा प्रदाता'], ['PSU IT departments', 'PSU आईटी विभाग']],
    interviewFocus: [
      ['Linux commands, permissions and networking', 'लिनक्स कमांड, अनुमतियाँ और नेटवर्किंग'],
      ['CI/CD design and container concepts', 'CI/CD डिज़ाइन और कंटेनर अवधारणाएँ'],
      ['Cloud services: compute, storage, IAM', 'क्लाउड सेवाएँ: कंप्यूट, स्टोरेज, IAM'],
      ['Troubleshooting a failing deployment', 'विफल डिप्लॉयमेंट की समस्या निवारण'],
    ],
    roadmap: [
      { m: 1, title: ['Linux + Networking', 'लिनक्स + नेटवर्किंग'], focus: ['Live in the terminal.', 'टर्मिनल में रहना सीखें।'], tasks: [['Shell, permissions, processes, systemd', 'शेल, अनुमतियाँ, प्रोसेस, systemd', ['linux']], ['TCP/IP, DNS, HTTP, SSH', 'TCP/IP, DNS, HTTP, SSH', ['networks']], ['Set up a Linux VM daily driver', 'रोज़ाना उपयोग के लिए लिनक्स VM', ['linux']]] },
      { m: 2, title: ['Git + Scripting', 'गिट + स्क्रिप्टिंग'], focus: ['Automate repetitive work.', 'दोहराए जाने वाले काम स्वचालित करें।'], tasks: [['Branching, rebasing, pull requests', 'ब्रांचिंग, रीबेसिंग, पुल रिक्वेस्ट', ['git']], ['Bash and Python automation scripts', 'बैश और पाइथन ऑटोमेशन स्क्रिप्ट', ['python', 'linux']], ['Automate a backup or report task', 'बैकअप या रिपोर्ट कार्य स्वचालित करें', ['python']]] },
      { m: 3, title: ['Containers', 'कंटेनर'], focus: ['Package anything, run anywhere.', 'कुछ भी पैकेज करें, कहीं भी चलाएँ।'], tasks: [['Dockerfiles, images, volumes', 'डॉकरफ़ाइल, इमेज, वॉल्यूम', ['docker']], ['Docker Compose multi-service app', 'डॉकर कंपोज़ मल्टी-सर्विस ऐप', ['docker']], ['Optimise image size and build cache', 'इमेज साइज़ और बिल्ड कैश अनुकूलित करें', ['docker']]] },
      { m: 4, title: ['Cloud + CI/CD', 'क्लाउड + CI/CD'], focus: ['Deploy on a real cloud account.', 'वास्तविक क्लाउड खाते पर डिप्लॉय करें।'], tasks: [['Free-tier cloud: compute, storage, IAM', 'मुफ़्त-टियर क्लाउड: कंप्यूट, स्टोरेज, IAM', ['cloud']], ['GitHub Actions pipeline for a project', 'प्रोजेक्ट के लिए GitHub Actions पाइपलाइन', ['git', 'docker']], ['Add monitoring and logging', 'मॉनिटरिंग और लॉगिंग जोड़ें', ['cloud', 'documentation']]] },
      { m: 5, title: ['Security + Resume', 'सुरक्षा + रिज़्यूमे'], focus: ['Reliability is a security topic.', 'विश्वसनीयता एक सुरक्षा विषय है।'], tasks: [['IAM, secrets, hardening basics', 'IAM, सीक्रेट्स, हार्डनिंग बुनियाद', ['security-basics']], ['DevOps resume with pipeline metrics', 'पाइपलाइन मेट्रिक्स वाला डेवऑप्स रिज़्यूमे', ['communication']], ['Document your home lab', 'अपना होम लैब दस्तावेज़ीकृत करें', ['documentation']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Troubleshooting under pressure.', 'दबाव में समस्या निवारण।'], tasks: [['3 DevOps mock interviews', '3 डेवऑप्स मॉक इंटरव्यू', ['communication']], ['Scenario-based troubleshooting drills', 'परिदृश्य-आधारित ट्रबलशूटिंग अभ्यास', ['problem-solving']], ['Revise OS and networks notes', 'OS और नेटवर्क नोट्स दोहराएँ', ['os', 'networks']]] },
    ],
  },
  {
    id: 'cybersecurity',
    icon: 'ShieldCheck',
    n: ['Cybersecurity Analyst', 'साइबर सुरक्षा विश्लेषक'],
    short: ['Detect, analyse and defend against attacks.', 'हमलों का पता लगाएँ, विश्लेषण करें और बचाव करें।'],
    difficulty: 3,
    interests: ['security', 'infra'],
    skills: [
      { id: 'security-basics', w: 3 }, { id: 'networks', w: 3 }, { id: 'linux', w: 3 }, { id: 'os', w: 2 },
      { id: 'python', w: 2 }, { id: 'documentation', w: 2 }, { id: 'problem-solving', w: 3 },
      { id: 'communication', w: 2 }, { id: 'time-management', w: 1 }, { id: 'cloud', w: 1 },
      { id: 'agile', w: 1 },
    ],
    responsibilities: [
      ['Monitor alerts and triage security events', 'अलर्ट मॉनिटर करना और सुरक्षा घटनाओं की जाँच'],
      ['Run vulnerability assessments on systems', 'सिस्टम पर भेद्यता मूल्यांकन चलाना'],
      ['Document incidents and remediation steps', 'घटनाएँ और सुधार चरण दस्तावेज़ीकृत करना'],
      ['Help teams follow secure coding practices', 'टीमों को सुरक्षित कोडिंग अपनाने में मदद'],
    ],
    oppCategories: [['SOC / security operations', 'SOC / सुरक्षा संचालन'], ['BFSI security teams', 'BFSI सुरक्षा टीम'], ['Government cyber cells', 'सरकारी साइबर सेल'], ['Consulting & audits', 'कंसल्टिंग और ऑडिट']],
    interviewFocus: [
      ['OSI model, TCP/IP, common attacks', 'OSI मॉडल, TCP/IP, सामान्य हमले'],
      ['OWASP Top 10 and secure coding', 'OWASP Top 10 और सुरक्षित कोडिंग'],
      ['Log analysis and incident response steps', 'लॉग विश्लेषण और घटना प्रतिक्रिया चरण'],
      ['Linux hardening and tooling', 'लिनक्स हार्डनिंग और टूलिंग'],
    ],
    roadmap: [
      { m: 1, title: ['Networks + Linux', 'नेटवर्क + लिनक्स'], focus: ['Security rests on fundamentals.', 'सुरक्षा बुनियाद पर टिकी है।'], tasks: [['TCP/IP, DNS, HTTP, TLS', 'TCP/IP, DNS, HTTP, TLS', ['networks']], ['Linux permissions, logs, processes', 'लिनक्स अनुमतियाँ, लॉग, प्रोसेस', ['linux']], ['Set up a safe practice VM', 'सुरक्षित अभ्यास VM बनाएँ', ['os']]] },
      { m: 2, title: ['Security Fundamentals', 'सुरक्षा बुनियाद'], focus: ['Threats, controls and terminology.', 'खतरे, नियंत्रण और शब्दावली।'], tasks: [['CIA triad, risk, controls', 'CIA ट्रायड, जोखिम, नियंत्रण', ['security-basics']], ['OWASP Top 10 with examples', 'OWASP Top 10 उदाहरण सहित', ['security-basics']], ['Password, hashing and auth basics', 'पासवर्ड, हैशिंग और auth बुनियाद', ['security-basics']]] },
      { m: 3, title: ['Offensive Basics', 'ऑफ़ेंसिव बुनियाद'], focus: ['Understand attacks to defend them.', 'बचाव के लिए हमलों को समझें।'], tasks: [['Guided labs on a legal practice platform', 'कानूनी अभ्यास प्लेटफ़ॉर्म पर गाइडेड लैब', ['security-basics', 'linux']], ['Scripting for automation in Python', 'पाइथन में ऑटोमेशन स्क्रिप्टिंग', ['python']], ['Document every lab finding', 'हर लैब खोज दस्तावेज़ीकृत करें', ['documentation']]] },
      { m: 4, title: ['Defensive Projects', 'डिफ़ेंसिव प्रोजेक्ट'], focus: ['Build a mini SOC at home.', 'घर पर मिनी SOC बनाएँ।'], tasks: [['Set up log collection and alerting', 'लॉग संग्रह और अलर्टिंग सेट करें', ['linux', 'documentation']], ['Write an incident response runbook', 'घटना प्रतिक्रिया रनबुक लिखें', ['documentation']], ['Vulnerability scan of a test system', 'टेस्ट सिस्टम का भेद्यता स्कैन', ['security-basics']]] },
      { m: 5, title: ['Certification + Resume', 'प्रमाणन + रिज़्यूमे'], focus: ['Prove it formally.', 'औपचारिक रूप से प्रमाणित करें।'], tasks: [['Prepare for an entry security certification (sample)', 'प्रवेश-स्तरीय सुरक्षा प्रमाणन की तैयारी (नमूना)', ['security-basics']], ['Security resume with lab evidence', 'लैब प्रमाण सहित सुरक्षा रिज़्यूमे', ['communication']], ['Publish a write-up portfolio', 'राइट-अप पोर्टफोलियो पब्लिश करें', ['documentation']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Scenario-driven answers.', 'परिदृश्य-आधारित उत्तर।'], tasks: [['3 security mock interviews', '3 सुरक्षा मॉक इंटरव्यू', ['communication']], ['Incident scenario drills', 'घटना परिदृश्य अभ्यास', ['problem-solving']], ['Apply to matched SOC roles', 'मैच्ड SOC रोल पर आवेदन', ['agile']]] },
    ],
  },
  {
    id: 'frontend-developer',
    icon: 'LayoutDashboard',
    n: ['Front-end Developer', 'फ्रंटएंड डेवलपर'],
    short: ['Craft fast, accessible interfaces users love.', 'तेज़, सुलभ इंटरफ़ेस बनाएँ जो उपयोगकर्ताओं को पसंद आएँ।'],
    difficulty: 2,
    interests: ['design', 'building-products'],
    skills: [
      { id: 'html-css', w: 3 }, { id: 'javascript', w: 3 }, { id: 'react', w: 3 }, { id: 'git', w: 3 },
      { id: 'design-thinking', w: 2 }, { id: 'figma', w: 1 }, { id: 'node', w: 1 }, { id: 'testing', w: 2 },
      { id: 'communication', w: 2 }, { id: 'creativity', w: 2 }, { id: 'documentation', w: 1 },
      { id: 'agile', w: 1 },
    ],
    responsibilities: [
      ['Convert designs into responsive components', 'डिज़ाइन को रिस्पॉन्सिव कंपोनेंट में बदलना'],
      ['Optimise performance and accessibility', 'परफ़ॉर्मेंस और सुलभता अनुकूलित करना'],
      ['Integrate APIs and manage UI state', 'API इंटीग्रेट करना और UI स्टेट प्रबंधित करना'],
      ['Collaborate with designers and backend engineers', 'डिज़ाइनर और बैकएंड इंजीनियरों के साथ सहयोग'],
    ],
    oppCategories: [['Product startups', 'प्रोडक्ट स्टार्टअप'], ['Agency & web teams', 'एजेंसी और वेब टीम'], ['Design systems teams', 'डिज़ाइन सिस्टम टीम'], ['Freelance', 'फ्रीलांस']],
    interviewFocus: [
      ['HTML/CSS layout challenges', 'HTML/CSS लेआउट चुनौतियाँ'],
      ['JavaScript closures, async, event loop', 'जावास्क्रिप्ट क्लोज़र, async, इवेंट लूप'],
      ['Framework state and component design', 'फ्रेमवर्क स्टेट और कंपोनेंट डिज़ाइन'],
      ['Accessibility and performance basics', 'सुलभता और परफ़ॉर्मेंस बुनियाद'],
    ],
    roadmap: [
      { m: 1, title: ['HTML + CSS', 'HTML + CSS'], focus: ['Layout mastery first.', 'पहले लेआउट में महारत।'], tasks: [['Semantic HTML and forms', 'सीमांटिक HTML और फ़ॉर्म', ['html-css']], ['Flexbox, grid, responsive design', 'फ्लेक्सबॉक्स, ग्रिड, रिस्पॉन्सिव डिज़ाइन', ['html-css']], ['Rebuild 3 real website layouts', '3 वास्तविक वेबसाइट लेआउट फिर बनाएँ', ['creativity']]] },
      { m: 2, title: ['JavaScript', 'जावास्क्रिप्ट'], focus: ['The language that decides hiring.', 'वह भाषा जो भर्ती तय करती है।'], tasks: [['ES6+, closures, promises, async/await', 'ES6+, क्लोज़र, प्रॉमिस, async/await', ['javascript']], ['DOM, events, fetch API', 'DOM, इवेंट, fetch API', ['javascript']], ['Build 5 mini apps without frameworks', 'फ्रेमवर्क के बिना 5 मिनी ऐप बनाएँ', ['javascript']]] },
      { m: 3, title: ['React + Git', 'रिऐक्ट + गिट'], focus: ['Component thinking and version control.', 'कंपोनेंट सोच और वर्ज़न कंट्रोल।'], tasks: [['Components, hooks, routing, state', 'कंपोनेंट, हुक, रूटिंग, स्टेट', ['react']], ['Consume a public API in a project', 'प्रोजेक्ट में पब्लिक API उपयोग करें', ['react', 'node']], ['Git workflow with pull requests', 'पुल रिक्वेस्ट के साथ गिट वर्कफ़्लो', ['git']]] },
      { m: 4, title: ['Projects + A11y', 'प्रोजेक्ट + सुलभता'], focus: ['Ship polished, accessible work.', 'परिष्कृत, सुलभ काम शिप करें।'], tasks: [['Build a full front-end portfolio project', 'पूरा फ्रंटएंड पोर्टफोलियो प्रोजेक्ट बनाएँ', ['react']], ['Keyboard and screen-reader testing', 'कीबोर्ड और स्क्रीन-रीडर टेस्टिंग', ['design-thinking', 'testing']], ['Lighthouse audit above 90', 'लाइटहाउस ऑडिट 90 से ऊपर', ['testing']]] },
      { m: 5, title: ['Resume + Portfolio', 'रिज़्यूमे + पोर्टफोलियो'], focus: ['Live demos beat descriptions.', 'लाइव डेमो विवरण से बेहतर हैं।'], tasks: [['Deploy portfolio site', 'पोर्टफोलियो साइट डिप्लॉय करें', ['documentation']], ['Front-end resume with demo links', 'डेमो लिंक वाला फ्रंटएंड रिज़्यूमे', ['communication']], ['Case study per project', 'हर प्रोजेक्ट पर केस स्टडी', ['presentation']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Live coding and UI rounds.', 'लाइव कोडिंग और UI राउंड।'], tasks: [['3 front-end mock interviews', '3 फ्रंटएंड मॉक इंटरव्यू', ['communication']], ['JS output and polyfill drills', 'JS आउटपुट और पॉलीफ़िल अभ्यास', ['javascript']], ['Apply to matched front-end roles', 'मैच्ड फ्रंटएंड रोल पर आवेदन', ['agile']]] },
    ],
  },
  {
    id: 'business-analyst',
    icon: 'Briefcase',
    n: ['Business / Product Analyst', 'बिज़नेस / प्रोडक्ट एनालिस्ट'],
    short: ['Bridge business needs and technical delivery.', 'व्यवसाय आवश्यकता और तकनीकी डिलीवरी के बीच पुल।'],
    difficulty: 2,
    interests: ['business', 'writing'],
    skills: [
      { id: 'communication', w: 3 }, { id: 'business-analysis', w: 3 }, { id: 'sql', w: 2 },
      { id: 'excel', w: 3 }, { id: 'presentation', w: 3 }, { id: 'documentation', w: 2 },
      { id: 'agile', w: 2 }, { id: 'problem-solving', w: 2 }, { id: 'statistics', w: 1 },
      { id: 'powerbi', w: 2 }, { id: 'teamwork', w: 2 }, { id: 'domain-finance', w: 1 },
    ],
    responsibilities: [
      ['Gather and document business requirements', 'व्यवसाय आवश्यकताएँ एकत्र और दस्तावेज़ीकृत करना'],
      ['Translate needs into user stories and specs', 'आवश्यकताओं को यूज़र स्टोरी और स्पेक में बदलना'],
      ['Analyse process data and recommend improvements', 'प्रक्रिया डेटा विश्लेषित कर सुझाव देना'],
      ['Coordinate between business and engineering teams', 'व्यवसाय और इंजीनियरिंग टीम में समन्वय'],
    ],
    oppCategories: [['Consulting & advisory', 'कंसल्टिंग और सलाह'], ['Product operations', 'प्रोडक्ट संचालन'], ['BFSI operations', 'BFSI संचालन'], ['Public sector projects', 'सार्वजनिक क्षेत्र परियोजनाएँ']],
    interviewFocus: [
      ['Requirement gathering scenario questions', 'आवश्यकता संग्रह परिदृश्य प्रश्न'],
      ['Metric trees, guesstimates and case logic', 'मेट्रिक ट्री, गेसटीमेट और केस तर्क'],
      ['Stakeholder conflict handling', 'हितधारक संघर्ष प्रबंधन'],
      ['SQL and Excel screening tests', 'SQL और एक्सेल स्क्रीनिंग टेस्ट'],
    ],
    roadmap: [
      { m: 1, title: ['Business Foundations', 'व्यवसाय बुनियाद'], focus: ['Learn how businesses make money.', 'सीखें कि व्यवसाय पैसा कैसे कमाते हैं।'], tasks: [['Read one sector annual report', 'एक क्षेत्र की वार्षिक रिपोर्ट पढ़ें', ['domain-finance']], ['Learn KPI, funnel and unit economics', 'KPI, फ़नेल और यूनिट इकोनॉमिक्स सीखें', ['business-analysis']], ['Excel: pivots, lookups, charts', 'एक्सेल: पिवट, लुकअप, चार्ट', ['excel']]] },
      { m: 2, title: ['Requirements & Agile', 'आवश्यकताएँ और एजाइल'], focus: ['Speak both languages fluently.', 'दोनों भाषाएँ धाराप्रवाह बोलें।'], tasks: [['Write user stories with acceptance criteria', 'स्वीकृति मानदंड के साथ यूज़र स्टोरी लिखें', ['documentation', 'agile']], ['Learn Scrum roles and ceremonies', 'स्क्रम भूमिकाएँ और सत्र सीखें', ['agile']], ['Document a process you know well', 'जिसे अच्छे से जानते हैं वह प्रक्रिया दस्तावेज़ीकृत करें', ['documentation']]] },
      { m: 3, title: ['SQL + Reporting', 'SQL + रिपोर्टिंग'], focus: ['Answer questions with data.', 'डेटा से प्रश्नों के उत्तर दें।'], tasks: [['SQL joins and aggregation', 'SQL join और एग्रीगेशन', ['sql']], ['Build a weekly KPI report', 'साप्ताहिक KPI रिपोर्ट बनाएँ', ['excel', 'powerbi']], ['Basic statistics for business', 'व्यवसाय के लिए बुनियादी सांख्यिकी', ['statistics']]] },
      { m: 4, title: ['Case Projects', 'केस प्रोजेक्ट'], focus: ['Solve real-shaped problems.', 'वास्तविक जैसे प्रश्न हल करें।'], tasks: [['Complete 5 case studies / guesstimates', '5 केस स्टडी / गेसटीमेट पूरे करें', ['problem-solving']], ['Build a dashboard for a mock client', 'मॉक क्लाइंट के लिए डैशबोर्ड बनाएँ', ['powerbi']], ['Present findings in 5 minutes', '5 मिनट में निष्कर्ष प्रस्तुत करें', ['presentation']]] },
      { m: 5, title: ['Resume + Communication', 'रिज़्यूमे + संचार'], focus: ['Clarity is the product.', 'स्पष्टता ही प्रोडक्ट है।'], tasks: [['Analyst resume with impact bullets', 'प्रभाव वाले बुलेट का एनालिस्ट रिज़्यूमे', ['communication']], ['Structured speaking practice (STAR)', 'संरचित बोलने का अभ्यास (STAR)', ['presentation']], ['LinkedIn positioning for BA roles', 'BA रोल्स के लिए लिंक्डइन पोज़िशनिंग', ['communication']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Cases under time pressure.', 'समय दबाव में केस।'], tasks: [['3 business analyst mock interviews', '3 बिज़नेस एनालिस्ट मॉक इंटरव्यू', ['communication']], ['Practise stakeholder scenarios', 'हितधारक परिदृश्य का अभ्यास', ['teamwork']], ['Apply to matched analyst roles', 'मैच्ड एनालिस्ट रोल पर आवेदन', ['agile']]] },
    ],
  },
  {
    id: 'product-manager',
    icon: 'Rocket',
    n: ['Associate Product Manager', 'एसोसिएट प्रोडक्ट मैनेजर'],
    short: ['Decide what to build and why it matters.', 'तय करें क्या बनाना है और वह क्यों मायने रखता है।'],
    difficulty: 3,
    interests: ['business', 'building-products', 'design'],
    skills: [
      { id: 'communication', w: 3 }, { id: 'problem-solving', w: 3 }, { id: 'business-analysis', w: 3 },
      { id: 'presentation', w: 3 }, { id: 'agile', w: 2 }, { id: 'documentation', w: 2 },
      { id: 'design-thinking', w: 2 }, { id: 'sql', w: 2 }, { id: 'statistics', w: 2 },
      { id: 'leadership', w: 3 }, { id: 'teamwork', w: 2 }, { id: 'creativity', w: 2 },
    ],
    responsibilities: [
      ['Research users and define problems worth solving', 'उपयोगकर्ताओं को समझें और हल करने योग्य समस्याएँ तय करें'],
      ['Write PRDs, roadmaps and success metrics', 'PRD, रोडमैप और सफलता मेट्रिक्स लिखें'],
      ['Prioritise backlog with engineering and design', 'इंजीनियरिंग और डिज़ाइन के साथ बैकलॉग प्राथमिकृत करें'],
      ['Analyse product data and iterate', 'प्रोडक्ट डेटा विश्लेषित करें और सुधारें'],
    ],
    oppCategories: [['Product startups', 'प्रोडक्ट स्टार्टअप'], ['Enterprise product teams', 'एंटरप्राइज़ प्रोडक्ट टीम'], ['Consulting → product', 'कंसल्टिंग → प्रोडक्ट'], ['Government digital missions', 'सरकारी डिजिटल मिशन']],
    interviewFocus: [
      ['Product sense: improve X for Y users', 'प्रोडक्ट सेंस: Y उपयोगकर्ताओं के लिए X सुधारें'],
      ['Prioritisation frameworks and trade-offs', 'प्राथमिकता फ्रेमवर्क और ट्रेड-ऑफ़'],
      ['Analytics: metric definition and interpretation', 'एनालिटिक्स: मेट्रिक परिभाषा और व्याख्या'],
      ['Behavioural: influence without authority', 'व्यवहारिक: अधिकार के बिना प्रभाव'],
    ],
    roadmap: [
      { m: 1, title: ['Product Thinking', 'प्रोडक्ट सोच'], focus: ['Fall in love with problems.', 'समस्याओं से प्रेम करें।'], tasks: [['Teardown 3 apps you use daily', 'रोज़ उपयोग किए 3 ऐप्स का विश्लेषण', ['design-thinking']], ['Learn JTBD and problem framing', 'JTBD और समस्या फ़्रेमिंग सीखें', ['business-analysis']], ['Interview 5 real users', '5 वास्तविक उपयोगकर्ताओं से बात करें', ['communication']]] },
      { m: 2, title: ['Metrics + Data', 'मेट्रिक्स + डेटा'], focus: ['Decide with evidence.', 'प्रमाण से निर्णय लें।'], tasks: [['Define north-star and guardrail metrics', 'नॉर्थ-स्टार और गार्डरेल मेट्रिक्स तय करें', ['statistics']], ['SQL for product analytics', 'प्रोडक्ट एनालिटिक्स के लिए SQL', ['sql']], ['Run one small experiment design', 'एक छोटा प्रयोग डिज़ाइन करें', ['statistics']]] },
      { m: 3, title: ['Delivery & Agile', 'डिलीवरी और एजाइल'], focus: ['Ship with a team.', 'टीम के साथ शिप करें।'], tasks: [['Write a PRD for your own idea', 'अपने आइडिया के लिए PRD लिखें', ['documentation']], ['Learn Scrum, estimation and backlog hygiene', 'स्क्रम, अनुमान और बैकलॉग अनुशासन सीखें', ['agile']], ['Shadow or join a build team', 'किसी बिल्ड टीम के साथ काम करें', ['teamwork']]] },
      { m: 4, title: ['Build Something', 'कुछ बनाएँ'], focus: ['PMs who ship are hired faster.', 'शिप करने वाले PM जल्दी भर्ती होते हैं।'], tasks: [['Launch a micro product or feature', 'माइक्रो प्रोडक्ट या फ़ीचर लॉन्च करें', ['creativity', 'leadership']], ['Collect feedback and iterate once', 'फ़ीडबैक लें और एक बार सुधारें', ['problem-solving']], ['Document learnings publicly', 'सीख सार्वजनिक रूप से दस्तावेज़ीकृत करें', ['documentation']]] },
      { m: 5, title: ['Storytelling + Resume', 'स्टोरीटेलिंग + रिज़्यूमे'], focus: ['Structure every answer.', 'हर उत्तर को संरचित करें।'], tasks: [['PM resume with shipped outcomes', 'शिप किए परिणामों वाला PM रिज़्यूमे', ['communication']], ['Practise product-sense answers aloud', 'प्रोडक्ट-सेंस उत्तर बोलकर अभ्यास करें', ['presentation']], ['Build a one-page portfolio', 'एक पेज का पोर्टफोलियो बनाएँ', ['documentation']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Framework + judgement.', 'फ्रेमवर्क + निर्णयशक्ति।'], tasks: [['3 product mock interviews', '3 प्रोडक्ट मॉक इंटरव्यू', ['communication']], ['Estimation and prioritisation drills', 'अनुमान और प्राथमिकता अभ्यास', ['problem-solving']], ['Apply to APM openings', 'APM पदों पर आवेदन करें', ['agile']]] },
    ],
  },
  {
    id: 'ui-ux-designer',
    icon: 'Palette',
    n: ['UI / UX Designer', 'UI / UX डिज़ाइनर'],
    short: ['Design experiences that are usable and beautiful.', 'उपयोगी और सुंदर अनुभव डिज़ाइन करें।'],
    difficulty: 2,
    interests: ['design', 'writing'],
    skills: [
      { id: 'design-thinking', w: 3 }, { id: 'figma', w: 3 }, { id: 'creativity', w: 3 },
      { id: 'communication', w: 3 }, { id: 'presentation', w: 2 }, { id: 'html-css', w: 2 },
      { id: 'problem-solving', w: 2 }, { id: 'documentation', w: 2 }, { id: 'teamwork', w: 2 },
      { id: 'adaptability', w: 1 }, { id: 'business-analysis', w: 1 },
    ],
    responsibilities: [
      ['Research users and map their journeys', 'उपयोगकर्ता अनुसंधान और उनकी यात्रा का मैपिंग'],
      ['Create wireframes, prototypes and design systems', 'वायरफ्रेम, प्रोटोटाइप और डिज़ाइन सिस्टम बनाना'],
      ['Run usability tests and iterate', 'उपयोगिता परीक्षण करना और सुधारना'],
      ['Hand off specs to engineering teams', 'इंजीनियरिंग टीम को स्पेक सौंपना'],
    ],
    oppCategories: [['Product design teams', 'प्रोडक्ट डिज़ाइन टीम'], ['Design agencies', 'डिज़ाइन एजेंसी'], ['Freelance & contract', 'फ्रीलांस और अनुबंध'], ['Government digital services', 'सरकारी डिजिटल सेवाएँ']],
    interviewFocus: [
      ['Portfolio walkthrough with design rationale', 'डिज़ाइन तर्क सहित पोर्टफोलियो वॉकथ्रू'],
      ['Whiteboard / app critique exercise', 'व्हाइटबोर्ड / ऐप समीक्षा अभ्यास'],
      ['Research methods and usability testing', 'रिसर्च विधियाँ और उपयोगिता परीक्षण'],
      ['Accessibility and design systems', 'सुलभता और डिज़ाइन सिस्टम'],
    ],
    roadmap: [
      { m: 1, title: ['Design Foundations', 'डिज़ाइन बुनियाद'], focus: ['Typography, colour, spacing, hierarchy.', 'टाइपोग्राफी, रंग, स्पेसिंग, श्रेणीक्रम।'], tasks: [['Learn visual design principles', 'विज़ुअल डिज़ाइन सिद्धांत सीखें', ['design-thinking']], ['Copy 10 well-designed screens', '10 अच्छी डिज़ाइन स्क्रीन कॉपी करें', ['figma']], ['Build a personal style reference board', 'व्यक्तिगत स्टाइल रेफ़रेंस बोर्ड बनाएँ', ['creativity']]] },
      { m: 2, title: ['Figma Fluency', 'फिग्मा दक्षता'], focus: ['Speed and structure in the tool.', 'टूल में गति और संरचना।'], tasks: [['Components, variants, auto-layout', 'कंपोनेंट, वेरिएंट, ऑटो-लेआउट', ['figma']], ['Design a mobile app flow', 'मोबाइल ऐप फ़्लो डिज़ाइन करें', ['design-thinking']], ['Learn accessible contrast rules', 'सुलभ कॉन्ट्रास्ट नियम सीखें', ['design-thinking']]] },
      { m: 3, title: ['UX Research', 'UX रिसर्च'], focus: ['Design from evidence.', 'प्रमाण से डिज़ाइन करें।'], tasks: [['User interviews and personas', 'उपयोगकर्ता इंटरव्यू और पर्सोना', ['business-analysis']], ['Journey maps and information architecture', 'जर्नी मैप और सूचना वास्तुकला', ['documentation']], ['Run a 5-user usability test', '5 उपयोगकर्ताओं का उपयोगिता परीक्षण', ['problem-solving']]] },
      { m: 4, title: ['Portfolio Projects', 'पोर्टफोलियो प्रोजेक्ट'], focus: ['Two strong case studies.', 'दो मज़बूत केस स्टडी।'], tasks: [['End-to-end case study #1', 'एंड-टू-एंड केस स्टडी #1', ['design-thinking', 'documentation']], ['Redesign an existing Indian product', 'किसी मौजूदा भारतीय प्रोडक्ट का रीडिज़ाइन', ['creativity']], ['Interactive prototype with flows', 'फ़्लो वाला इंटरैक्टिव प्रोटोटाइप', ['figma']]] },
      { m: 5, title: ['Code Basics + Resume', 'कोड बुनियाद + रिज़्यूमे'], focus: ['Collaborate better with engineers.', 'इंजीनियरों के साथ बेहतर सहयोग।'], tasks: [['HTML/CSS basics for handoff', 'हैंडऑफ़ के लिए HTML/CSS बुनियाद', ['html-css']], ['Design resume with portfolio link', 'पोर्टफोलियो लिंक वाला डिज़ाइन रिज़्यूमे', ['communication']], ['Write case study narratives', 'केस स्टडी कथाएँ लिखें', ['presentation']]] },
      { m: 6, title: ['Interview Prep', 'इंटरव्यू तैयारी'], focus: ['Present, critique, defend.', 'प्रस्तुत करें, समीक्षा करें, बचाव करें।'], tasks: [['3 design mock interviews', '3 डिज़ाइन मॉक इंटरव्यू', ['communication']], ['App critique drills', 'ऐप समीक्षा अभ्यास', ['design-thinking']], ['Apply to matched design roles', 'मैच्ड डिज़ाइन रोल पर आवेदन', ['teamwork']]] },
    ],
  },
];

export const CAREER_BY_ID = Object.fromEntries(CAREERS.map((c) => [c.id, c]));

/** Quick keyword map used by the chatbot/demo NLU and by resume keyword checks. */
export const CAREER_KEYWORDS = {
  'software-developer': ['software', 'developer', 'sde', 'engineer', 'coding', 'backend', 'full stack', 'fullstack', 'सॉफ्टवेयर', 'डेवलपर', 'कोडिंग'],
  'data-analyst': ['data analyst', 'analytics', 'analyst', 'sql', 'power bi', 'tableau', 'डेटा एनालिस्ट', 'एनालिटिक्स'],
  'ai-ml-engineer': ['ai', 'ml', 'machine learning', 'deep learning', 'data science', 'एआई', 'मशीन लर्निंग', 'डेटा साइंस'],
  'cloud-devops': ['cloud', 'devops', 'aws', 'azure', 'docker', 'kubernetes', 'sre', 'क्लाउड', 'डेवऑप्स'],
  cybersecurity: ['security', 'cyber', 'soc', 'ethical hacking', 'vapt', 'साइबर', 'सुरक्षा'],
  'frontend-developer': ['frontend', 'front end', 'react', 'ui developer', 'web developer', 'फ्रंटएंड', 'वेब'],
  'business-analyst': ['business analyst', 'product analyst', 'consultant', 'bba', 'बिज़नेस एनालिस्ट'],
  'product-manager': ['product manager', 'apm', 'pm', 'product', 'प्रोडक्ट मैनेजर'],
  'ui-ux-designer': ['design', 'designer', 'ux', 'ui', 'figma', 'डिज़ाइन', 'डिज़ाइनर'],
};

export default CAREERS;
