/**
 * Project Lab catalog — portfolio projects recommended from target career + skill gaps.
 * Every project states the problem, the stack, the learning outcome and a GitHub checklist,
 * because "I built X" only counts when the evidence is visible.
 */

export const PROJECTS = [
  { id: 'p1', t: ['Campus Placement Tracker', 'कैंपस प्लेसमेंट ट्रैकर'], careers: ['software-developer', 'frontend-developer'], skills: ['react', 'node', 'sql', 'git'], diff: 'intermediate', weeks: 4,
    problem: ['Students lose track of applications across portals and spreadsheets; placement cells cannot see cohort progress.', 'छात्र कई पोर्टल और स्प्रेडशीट में अपने आवेदन खो देते हैं; प्लेसमेंट सेल कोहोर्ट प्रगति नहीं देख पाती।'],
    stack: ['React front end, Node/Express API, SQL database, GitHub Actions deploy', 'रिऐक्ट फ्रंटएंड, नोड/एक्सप्रेस API, SQL डेटाबेस, GitHub Actions डिप्लॉय'],
    outcome: ['Full-stack CRUD, auth, schema design and deployment in one project.', 'एक ही प्रोजेक्ट में फुल-स्टैक CRUD, auth, स्कीमा डिज़ाइन और डिप्लॉयमेंट।'],
    checklist: [['README with screenshots and setup steps', 'स्क्रीनशॉट और सेटअप चरणों वाला README'], ['ER diagram and API contract', 'ER डायग्राम और API कॉन्ट्रैक्ट'], ['At least 10 clean commits', 'कम से कम 10 साफ़ कमिट'], ['Live demo link', 'लाइव डेमो लिंक'], ['Basic test coverage', 'बेसिक टेस्ट कवरेज']] },
  { id: 'p2', t: ['SQL Sales Analytics Report', 'SQL सेल्स एनालिटिक्स रिपोर्ट'], careers: ['data-analyst', 'business-analyst'], skills: ['sql', 'excel', 'statistics', 'documentation'], diff: 'beginner', weeks: 2,
    problem: ['A retail store manager wants to know which products and regions are actually growing.', 'एक रिटेल स्टोर मैनेजर जानना चाहता है कि कौन से प्रोडक्ट और क्षेत्र वास्तव में बढ़ रहे हैं।'],
    stack: ['Public sample dataset, SQL (CTEs + window functions), spreadsheet summary', 'सार्वजनिक नमूना डेटासेट, SQL (CTE + विंडो फंक्शन), स्प्रेडशीट सारांश'],
    outcome: ['Query design, metric definition and written interpretation.', 'क्वेरी डिज़ाइन, मेट्रिक परिभाषा और लिखित व्याख्या।'],
    checklist: [['The business question written at the top of the README', 'README के शीर्ष पर व्यवसाय प्रश्न लिखा हो'], ['SQL file with comments', 'कमेंट वाली SQL फ़ाइल'], ['3 charts with titles and units', 'शीर्षक और इकाई वाले 3 चार्ट'], ['One-page findings summary', 'एक पेज का निष्कर्ष सारांश']] },
  { id: 'p3', t: ['Interactive KPI Dashboard', 'इंटरैक्टिव KPI डैशबोर्ड'], careers: ['data-analyst', 'business-analyst', 'product-manager'], skills: ['powerbi', 'sql', 'presentation'], diff: 'intermediate', weeks: 3,
    problem: ['Leadership reviews five separate reports and still cannot answer “what changed this week?”.', 'नेतृत्व पाँच अलग-अलग रिपोर्ट देखता है फिर भी “इस सप्ताह क्या बदला?” का उत्तर नहीं मिलता।'],
    stack: ['Power BI or Tableau, SQL view layer, recorded walkthrough', 'पावर BI या टैब्लो, SQL व्यू लेयर, रिकॉर्डेड वॉकथ्रू'],
    outcome: ['Dashboard storytelling and stakeholder-ready communication.', 'डैशबोर्ड स्टोरीटेलिंग और हितधारक-तैयार संचार।'],
    checklist: [['Metric definitions documented', 'मेट्रिक परिभाषाएँ दस्तावेज़ीकृत'], ['Filters that answer a real question', 'फ़िल्टर जो वास्तविक प्रश्न का उत्तर दें'], ['3-minute recorded walkthrough', '3 मिनट का रिकॉर्डेड वॉकथ्रू'], ['Accessibility: colour-blind safe palette', 'सुलभता: रंग-अंधता सुरक्षित पैलेट']] },
  { id: 'p4', t: ['Handwritten Digit Classifier', 'हस्तलिखित अंक क्लासिफ़ायर'], careers: ['ai-ml-engineer'], skills: ['python', 'ml', 'statistics'], diff: 'beginner', weeks: 2,
    problem: ['Build your first end-to-end model: data in, trained model out, accuracy explained.', 'अपना पहला एंड-टू-एंड मॉडल बनाएँ: डेटा इन, ट्रेन्ड मॉडल आउट, सटीकता की व्याख्या।'],
    stack: ['Python, scikit-learn, a public image dataset, notebook + script', 'पाइथन, scikit-learn, सार्वजनिक इमेज डेटासेट, नोटबुक + स्क्रिप्ट'],
    outcome: ['Train/test discipline, metrics selection and error analysis.', 'ट्रेन/टेस्ट अनुशासन, मेट्रिक चयन और त्रुटि विश्लेषण।'],
    checklist: [['Notebook runs top-to-bottom without edits', 'नोटबुक बिना बदलाव के ऊपर से नीचे चले'], ['Confusion matrix and error examples', 'कन्फ़्यूज़न मैट्रिक्स और त्रुटि उदाहरण'], ['Why this metric was chosen', 'यह मेट्रिक क्यों चुना गया'], ['requirements.txt', 'requirements.txt']] },
  { id: 'p5', t: ['Deployed ML API with Monitoring', 'मॉनिटरिंग वाला डिप्लॉय्ड ML API'], careers: ['ai-ml-engineer', 'cloud-devops'], skills: ['ml', 'docker', 'cloud', 'node'], diff: 'advanced', weeks: 5,
    problem: ['A notebook cannot serve users. Ship a model behind an API with logging and health checks.', 'नोटबुक उपयोगकर्ताओं की सेवा नहीं कर सकती। मॉडल को लॉगिंग और हेल्थ चेक वाले API के पीछे शिप करें।'],
    stack: ['FastAPI or Node service, Docker, free cloud tier, structured logs', 'FastAPI या नोड सेवा, डॉकर, मुफ़्त क्लाउड टियर, संरचित लॉग'],
    outcome: ['MLOps fundamentals: packaging, deployment, observability.', 'MLOps बुनियाद: पैकेजिंग, डिप्लॉयमेंट, ऑब्ज़र्वेबिलिटी।'],
    checklist: [['Dockerfile and compose file', 'डॉकरफ़ाइल और कंपोज़ फ़ाइल'], ['Public API endpoint with docs', 'डॉक्स वाला सार्वजनिक API एंडपॉइंट'], ['Request logging and error handling', 'रिक्वेस्ट लॉगिंग और त्रुटि प्रबंधन'], ['Architecture diagram', 'आर्किटेक्चर डायग्राम']] },
  { id: 'p6', t: ['Automated CI/CD Pipeline Lab', 'स्वचालित CI/CD पाइपलाइन लैब'], careers: ['cloud-devops', 'software-developer'], skills: ['git', 'docker', 'cloud', 'linux'], diff: 'intermediate', weeks: 3,
    problem: ['Manual deployments break. Build a pipeline that tests, containerises and deploys on every push.', 'मैन्युअल डिप्लॉयमेंट टूटते हैं। हर पुश पर टेस्ट, कंटेनराइज़ और डिप्लॉय करने वाली पाइपलाइन बनाएँ।'],
    stack: ['GitHub Actions, Docker, a cloud free tier, IaC basics', 'GitHub Actions, डॉकर, क्लाउड मुफ़्त टियर, IaC बुनियाद'],
    outcome: ['Pipeline design, build caching and deployment safety.', 'पाइपलाइन डिज़ाइन, बिल्ड कैशिंग और डिप्लॉयमेंट सुरक्षा।'],
    checklist: [['Pipeline YAML in the repo', 'repo में पाइपलाइन YAML'], ['Green build badge in README', 'README में हरा बिल्ड बैज'], ['Rollback strategy documented', 'रोलबैक रणनीति दस्तावेज़ीकृत'], ['Screenshots of deployment', 'डिप्लॉयमेंट के स्क्रीनशॉट']] },
  { id: 'p7', t: ['Home SOC with Log Alerting', 'लॉग अलर्टिंग वाला होम SOC'], careers: ['cybersecurity', 'cloud-devops'], skills: ['linux', 'security-basics', 'networks', 'documentation'], diff: 'advanced', weeks: 4,
    problem: ['Detect suspicious SSH activity on your own machine and alert yourself — the smallest real SOC.', 'अपनी मशीन पर संदिग्ध SSH गतिविधि का पता लगाएँ और स्वयं को अलर्ट करें — सबसे छोटा वास्तविक SOC।'],
    stack: ['Linux VM, log collector, alerting script, written runbook', 'लिनक्स VM, लॉग कलेक्टर, अलर्टिंग स्क्रिप्ट, लिखित रनबुक'],
    outcome: ['Log analysis, detection logic and incident documentation.', 'लॉग विश्लेषण, डिटेक्शन लॉजिक और घटना दस्तावेज़ीकरण।'],
    checklist: [['Detection rules explained', 'डिटेक्शन नियम समझाए गए'], ['Sample incident write-up', 'नमूना घटना राइट-अप'], ['Runbook for response steps', 'प्रतिक्रिया चरणों का रनबुक'], ['Legal & ethical scope statement', 'कानूनी और नैतिक दायरा कथन']] },
  { id: 'p8', t: ['Accessible College Website Rebuild', 'सुलभ कॉलेज वेबसाइट रीबिल्ड'], careers: ['frontend-developer', 'ui-ux-designer'], skills: ['html-css', 'javascript', 'design-thinking', 'react'], diff: 'beginner', weeks: 3,
    problem: ['Most college sites fail keyboard and contrast checks. Rebuild one page properly.', 'ज्यादातर कॉलेज साइटें कीबोर्ड और कॉन्ट्रास्ट जाँच में विफल होती हैं। एक पेज सही तरह फिर बनाएँ।'],
    stack: ['Semantic HTML, CSS grid/flex, minimal JS, Lighthouse audit', 'सीमांटिक HTML, CSS ग्रिड/फ़्लेक्स, कम JS, लाइटहाउस ऑडिट'],
    outcome: ['Responsive layout, accessibility and performance auditing.', 'रिस्पॉन्सिव लेआउट, सुलभता और परफ़ॉर्मेंस ऑडिटिंग।'],
    checklist: [['Before/after Lighthouse scores', 'पहले/बाद के लाइटहाउस स्कोर'], ['Keyboard-only navigation works', 'केवल कीबोर्ड नेविगेशन काम करे'], ['Contrast ratios documented', 'कॉन्ट्रास्ट अनुपात दस्तावेज़ीकृत'], ['Mobile and desktop screenshots', 'मोबाइल और डेस्कटॉप स्क्रीनशॉट']] },
  { id: 'p9', t: ['E-commerce Product UI Kit', 'ई-कॉमर्स प्रोडक्ट UI किट'], careers: ['frontend-developer', 'ui-ux-designer'], skills: ['react', 'figma', 'javascript', 'creativity'], diff: 'intermediate', weeks: 4,
    problem: ['Teams rebuild the same buttons and cards endlessly. Build a reusable component library.', 'टीमें बार-बार वही बटन और कार्ड बनाती हैं। पुन: प्रयोज्य कंपोनेंट लाइब्रेरी बनाएँ।'],
    stack: ['React components, design tokens, Storybook-style demo page', 'रिऐक्ट कंपोनेंट, डिज़ाइन टोकन, स्टोरीबुक-शैली डेमो पेज'],
    outcome: ['Component architecture, design tokens and documentation.', 'कंपोनेंट आर्किटेक्चर, डिज़ाइन टोकन और दस्तावेज़ीकरण।'],
    checklist: [['Token system documented', 'टोकन सिस्टम दस्तावेज़ीकृत'], ['Dark mode support', 'डार्क मोड सपोर्ट'], ['Component usage examples', 'कंपोनेंट उपयोग उदाहरण'], ['Live demo deployed', 'लाइव डेमो डिप्लॉय्ड']] },
  { id: 'p10', t: ['UX Case Study: Local Service App', 'UX केस स्टडी: स्थानीय सेवा ऐप'], careers: ['ui-ux-designer', 'product-manager'], skills: ['design-thinking', 'figma', 'communication', 'business-analysis'], diff: 'intermediate', weeks: 3,
    problem: ['A neighbourhood service (salon, repairs, tuition) still runs on phone calls. Design its digital flow.', 'एक मोहल्ले की सेवा (सैलून, मरम्मत, ट्यूशन) अब भी फ़ोन कॉल पर चलती है। उसका डिजिटल फ़्लो डिज़ाइन करें।'],
    stack: ['User interviews, personas, journey map, Figma prototype', 'उपयोगकर्ता इंटरव्यू, पर्सोना, जर्नी मैप, फिग्मा प्रोटोटाइप'],
    outcome: ['Research-to-prototype thinking and case-study storytelling.', 'रिसर्च-से-प्रोटोटाइप सोच और केस-स्टडी स्टोरीटेलिंग।'],
    checklist: [['5 interview notes summarised', '5 इंटरव्यू नोट्स का सारांश'], ['Problem statement in one line', 'एक पंक्ति में समस्या कथन'], ['Before/after flow comparison', 'पहले/बाद फ़्लो तुलना'], ['Clickable prototype link', 'क्लिक करने योग्य प्रोटोटाइप लिंक']] },
  { id: 'p11', t: ['Requirement Doc for a Real Feature', 'वास्तविक फ़ीचर के लिए रिक्वायरमेंट डॉक'], careers: ['business-analyst', 'product-manager'], skills: ['business-analysis', 'documentation', 'agile', 'communication'], diff: 'beginner', weeks: 2,
    problem: ['Engineers build the wrong thing because requirements were never written down.', 'आवश्यकताएँ कभी लिखी नहीं गईं इसलिए इंजीनियर गलत चीज़ बनाते हैं।'],
    stack: ['PRD template, user stories with acceptance criteria, flow diagram', 'PRD टेम्पलेट, स्वीकृति मानदंड वाली यूज़र स्टोरी, फ़्लो डायग्राम'],
    outcome: ['Requirement engineering and specification clarity.', 'रिक्वायरमेंट इंजीनियरिंग और स्पष्ट स्पेसिफ़िकेशन।'],
    checklist: [['Problem, users and success metrics defined', 'समस्या, उपयोगकर्ता और सफलता मेट्रिक्स परिभाषित'], ['8–12 user stories with criteria', 'मानदंड वाली 8–12 यूज़र स्टोरी'], ['Out-of-scope section', 'दायरे से बाहर का सेक्शन'], ['Open questions list', 'खुले प्रश्नों की सूची']] },
  { id: 'p12', t: ['Automated Report Bot', 'स्वचालित रिपोर्ट बॉट'], careers: ['data-analyst', 'software-developer'], skills: ['python', 'sql', 'excel', 'documentation'], diff: 'beginner', weeks: 2,
    problem: ['A weekly report takes two hours of manual copying. Automate it end to end.', 'साप्ताहिक रिपोर्ट में दो घंटे की मैनुअल कॉपिंग लगती है। इसे पूरी तरह स्वचालित करें।'],
    stack: ['Python, SQL queries, spreadsheet or email output, cron/GitHub schedule', 'पाइथन, SQL क्वेरी, स्प्रेडशीट या ईमेल आउटपुट, cron/GitHub शेड्यूल'],
    outcome: ['Automation thinking and measurable time saved.', 'ऑटोमेशन सोच और मापने योग्य बचा समय।'],
    checklist: [['Before/after time comparison', 'पहले/बाद समय तुलना'], ['Configurable date range', 'कॉन्फ़िगर करने योग्य तिथि सीमा'], ['Error handling for empty data', 'खाली डेटा के लिए त्रुटि प्रबंधन'], ['Usage instructions', 'उपयोग निर्देश']] },
  { id: 'p13', t: ['Chat Assistant for College FAQs', 'कॉलेज FAQ के लिए चैट सहायक'], careers: ['ai-ml-engineer', 'software-developer'], skills: ['python', 'node', 'ml', 'communication'], diff: 'intermediate', weeks: 4,
    problem: ['Students ask the same admission, exam and hostel questions every week.', 'छात्र हर सप्ताह वही प्रवेश, परीक्षा और हॉस्टल प्रश्न पूछते हैं।'],
    stack: ['Retrieval over a small FAQ corpus, simple API, chat UI', 'छोटे FAQ कॉर्पस पर रिट्रीवल, सरल API, चैट UI'],
    outcome: ['Retrieval pipelines, evaluation and product thinking.', 'रिट्रीवल पाइपलाइन, मूल्यांकन और प्रोडक्ट सोच।'],
    checklist: [['Evaluation set with sample answers', 'नमूना उत्तरों वाला मूल्यांकन सेट'], ['Fallback for unknown questions', 'अज्ञात प्रश्नों के लिए फ़ॉलबैक'], ['Bilingual responses (English / हिंदी)', 'द्विभाषी उत्तर (English / हिंदी)'], ['Architecture note', 'आर्किटेक्चर नोट']] },
  { id: 'p14', t: ['Inventory System for a Small Shop', 'छोटी दुकान के लिए इन्वेंटरी सिस्टम'], careers: ['software-developer', 'business-analyst'], skills: ['sql', 'dbms', 'node', 'react'], diff: 'intermediate', weeks: 4,
    problem: ['A local shop tracks stock in notebooks and loses money on reorders.', 'एक स्थानीय दुकान नोटबुक में स्टॉक रखती है और रीऑर्डर में नुकसान उठाती है।'],
    stack: ['SQL schema, REST API, simple web UI, barcode-style entry', 'SQL स्कीमा, REST API, सरल वेब UI, बारकोड-शैली एंट्री'],
    outcome: ['Schema normalisation, business rules and user empathy.', 'स्कीमा नॉर्मलाइज़ेशन, बिज़नेस नियम और उपयोगकर्ता सहानुभूति।'],
    checklist: [['ER diagram and normalisation notes', 'ER डायग्राम और नॉर्मलाइज़ेशन नोट्स'], ['Low-stock alert logic', 'कम-स्टॉक अलर्ट लॉजिक'], ['Interview notes with the shop owner', 'दुकानदार के साथ इंटरव्यू नोट्स'], ['Demo video under 3 minutes', '3 मिनट से कम डेमो वीडियो']] },
  { id: 'p15', t: ['Open-Source Contribution Sprint', 'ओपन-सोर्स योगदान स्प्रिंट'], careers: ['software-developer', 'frontend-developer', 'cloud-devops'], skills: ['git', 'sdlc', 'documentation', 'communication'], diff: 'intermediate', weeks: 3,
    problem: ['Recruiters want proof you can work in an existing codebase, not only your own.', 'भर्तीकर्ता चाहते हैं कि आप मौजूदा कोडबेस में काम कर सकते हों, केवल अपने में नहीं।'],
    stack: ['A public repo, issue triage, branch + pull request workflow', 'एक पब्लिक repo, इशू ट्रायाज, ब्रांच + पुल रिक्वेस्ट वर्कफ़्लो'],
    outcome: ['Real collaboration: reviews, discussion and merged changes.', 'वास्तविक सहयोग: रिव्यू, चर्चा और मर्ज किए बदलाव।'],
    checklist: [['3 issues explored and documented', '3 इशू देखे और दस्तावेज़ीकृत'], ['At least 1 pull request submitted', 'कम से कम 1 पुल रिक्वेस्ट जमा'], ['Review comments addressed', 'रिव्यू टिप्पणियों पर काम'], ['Links in README', 'README में लिंक']] },
  { id: 'p16', t: ['Government Scheme Finder', 'सरकारी योजना फ़ाइंडर'], careers: ['frontend-developer', 'software-developer', 'product-manager'], skills: ['react', 'sql', 'design-thinking', 'documentation'], diff: 'intermediate', weeks: 4,
    problem: ['Eligible students miss scholarships and schemes because information is scattered across portals.', 'योग्य छात्र स्कॉलरशिप और योजनाएँ चूक जाते हैं क्योंकि जानकारी कई पोर्टलों पर बिखरी है।'],
    stack: ['Structured dataset, React filter UI, eligibility logic, bilingual labels', 'संरचित डेटासेट, रिऐक्ट फ़िल्टर UI, पात्रता लॉजिक, द्विभाषी लेबल'],
    outcome: ['Public-interest product thinking plus data structuring.', 'जन-हित प्रोडक्ट सोच और डेटा संरचना।'],
    checklist: [['Data sources cited clearly', 'डेटा स्रोत स्पष्ट रूप से उद्धृत'], ['Eligibility rules documented', 'पात्रता नियम दस्तावेज़ीकृत'], ['English and हिंदी interface', 'English और हिंदी इंटरफ़ेस'], ['Disclaimer about verifying officially', 'आधिकारिक सत्यापन का अस्वीकरण']] },
  { id: 'p17', t: ['Personal Finance Insight Dashboard', 'व्यक्तिगत वित्त अंतर्दृष्टि डैशबोर्ड'], careers: ['data-analyst', 'business-analyst'], skills: ['excel', 'sql', 'powerbi', 'statistics'], diff: 'beginner', weeks: 2,
    problem: ['Understand where money actually goes using your own (anonymised) transactions.', 'अपने स्वयं के (गुमनाम) लेन-देन से समझें कि पैसा वास्तव में कहाँ जाता है।'],
    stack: ['CSV export, SQL or spreadsheet analysis, dashboard, written insight', 'CSV निर्यात, SQL या स्प्रेडशीट विश्लेषण, डैशबोर्ड, लिखित अंतर्दृष्टि'],
    outcome: ['Metric design and turning numbers into a recommendation.', 'मेट्रिक डिज़ाइन और संख्याओं को सिफारिश में बदलना।'],
    checklist: [['Privacy note: no real account details', 'गोपनीयता नोट: कोई वास्तविक खाता विवरण नहीं'], ['Categories defined and justified', 'श्रेणियाँ परिभाषित और उचित'], ['One actionable recommendation', 'एक व्यावहारिक सिफारिश'], ['Dashboard screenshot', 'डैशबोर्ड स्क्रीनशॉट']] },
  { id: 'p18', t: ['API Test Automation Suite', 'API टेस्ट ऑटोमेशन सूट'], careers: ['software-developer', 'cloud-devops'], skills: ['testing', 'postman', 'python', 'documentation'], diff: 'intermediate', weeks: 3,
    problem: ['Manual API checks miss regressions. Build a repeatable test suite with reporting.', 'मैनुअल API जाँच रिग्रेशन चूक जाती है। रिपोर्टिंग के साथ दोहराने योग्य टेस्ट सूट बनाएँ।'],
    stack: ['Postman collections or Python test scripts, CI runner, HTML report', 'पोस्टमैन कलेक्शन या पाइथन टेस्ट स्क्रिप्ट, CI रनर, HTML रिपोर्ट'],
    outcome: ['Test design, automation discipline and CI integration.', 'टेस्ट डिज़ाइन, ऑटोमेशन अनुशासन और CI इंटीग्रेशन।'],
    checklist: [['Coverage list of endpoints tested', 'टेस्ट किए एंडपॉइंट की सूची'], ['Failing test intentionally included', 'जानबूझकर एक विफल टेस्ट शामिल'], ['CI run on every push', 'हर पुश पर CI रन'], ['Report artefact saved', 'रिपोर्ट आर्टिफ़ैक्ट सेव']] },
];

export const PROJECT_BY_ID = Object.fromEntries(PROJECTS.map((p) => [p.id, p]));
export default PROJECTS;
